# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Silver Strand Physical Therapy
email: admin@silverstrandpt.com
description: > # this means to ignore newlines until "baseurl:"
  Silver Stand Physical Therapy provides physical therapy services
  to patients throughout Imperial Beach and the South Bay. Schedule
  an initial evaluation today!
baseurl: "/silver-strand-pt" # the subpath of dev site, e.g. /silver-strand-pt <-- Change this to "" before pushing to FTP
url: "http://silverstrandpt.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude:
  - "*.sketch"
